config/routes.rb
Wishlist::Application.routes.draw do
  root 'static_pages#root'

  match '/home', to: 'static_pages#home', via: :get, as: :home

  match '/signin', to: 'sessions#new', via: :get, as: :signin
  match '/signup', to: 'users#new', via: :get, as: :signup
  match '/signout', to: 'sessions#destroy', via: 'delete', as: :signout

  match '/users/search', to: 'users#search', via: 'get', as: :user_search
  match '/users/add_friend', to: 'users#add_friend', via: 'post', as: :add_friend
  match '/users/accept_friend', to: 'users#accept_friend', via: 'post', as: :accept_friend
  match '/users/deny_friend', to: 'users#deny_friend', via: 'post', as: :deny_friend
  match '/users/buy_gift', to: 'users#buy_gift', via: 'post', as: :buy_user_gift
  match '/users/mark_gift_request_purchased', to: 'users#mark_gift_request_purchased', via: 'post', as: :mark_gift_request_purchased
  match '/users/delete_gift_request', to: 'users#delete_gift_request', via: 'delete', as: :delete_gift_request

  resources :users, only: [:new, :create, :show, :index, :update]
  resources :sessions, only: [:new, :create, :destroy]
end

app/models/user.rb
class User < ActiveRecord::Base
  validates :email, presence: true, uniqueness: { case_sensitive: false }, format: { with: ApplicationHelper.email_regex }
  validates :full_name, presence: true, format: { with: /.+\s.+/, message: 'requires first and last name.' }

  has_many :remember_tokens, dependent: :destroy

  has_many :regular_friendships, foreign_key: :user_id, class_name: 'Friendship', dependent: :destroy
  has_many :inverse_friendships, foreign_key: :friend_id, class_name: 'Friendship', dependent: :destroy

  has_many :gift_requests, dependent: :destroy
  has_many :gifts, dependent: :destroy
  has_many :gifts_purchased, foreign_key: :buyer_user_id, class_name: 'Gift', inverse_of: :buyer, dependent: :destroy

  accepts_nested_attributes_for :gift_requests, allow_destroy: true

  has_secure_password

  scope :by_search, ->(search_term) {
    if search_term.nil?
      none
    else
      where( 'full_name ilike any(array[?]) or email ilike ?', search_term.split( " " ).map{ |term| "%#{term}%" }, "%#{search_term}%" )
    end
  }

  before_save do
    self.email = email.downcase
  end

  def first_name
    self.full_name.split( ' ' )[0]
  end

  def friends
    User.find( friend_ids )
  end

  def has_friend?( user )
    self.has_friend_with_id?( user.id )
  end

  def has_friend_with_id?( user_id )
    Friendship.where( '((user_id = ? and friend_id = ?) or (friend_id = ? and user_id = ?)) and accepted = ?', user_id, self.id, user_id, self.id, true ).exists?
  end

  def friend_requests( options = {} )
    scope = Friendship

    if options[:include_friends]
      scope = scope.with_friend
    end

    if options[:include_users]
      scope = scope.with_user
    end

    scope.where( 'friend_id = ? and accepted = ?', self.id, false )
  end

  def pending_request( friend )
    Friendship.find_by( 'user_id = ? and friend_id = ? and accepted = ?', self.id, friend.id, false )
  end

  def header_link_text
    num_friend_requests = self.friend_requests.count
    'My Account' + (num_friend_requests > 0 ? " (#{num_friend_requests})" : '')
  end

  private
  def friend_ids
    regular_friend_ids = self.regular_friendships.select{
      |friendship| friendship.accepted?
    }.map{
      |friendship| friendship.friend_id
    }

    inverse_friend_ids = self.inverse_friendships.select{
      |friendship| friendship.accepted?
    }.map{
      |friendship| friendship.user_id
    }

    regular_friend_ids.concat( inverse_friend_ids )
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_action :signed_in_user, except: [:new, :create, :update, :mark_gift_request_purchased, :delete_gift_request]
  before_action :correct_user, only: [:update]

  def new
    @user = User.new
  end

  def create
    @user = User.new( user_params )
    if @user.save
      flash[:success] = 'Welcome to WishList'
      sign_in( @user )
      redirect_to user_path( @user )
    else
      render 'new'
    end
  end

  def show
    @user = User.find( params[:id] )
  end

  def index
    if params[:search]
      @users = User.by_search( params[:search] ).where( "id != ?", current_user.id )
    else
      @users = []
    end
  end

  def update
    user = User.find( params[:id] )

    params[:user][:gift_requests_attributes].each do |key, hash|
      hash[:user_id] = user.id
      GiftRequest.create( hash )
    end

    redirect_to user_path( user )
  end

  def search
    @users = User.by_search( params[:search] ).where( "id != ?", current_user.id )
    respond_to do |format|
      format.json
    end
  end

  def add_friend
    @friend = User.find( params[:friend_id] )
    Friendship.create( :friend_id => @friend.id, :user_id => current_user.id )
    flash[:success] = 'Friend added!'
    redirect_to users_path
  end

  def accept_friend
    @request = Friendship.find( params[:friendship_id] )

    if @request.friend_id == current_user.id
      @request.update_attribute( :accepted, true )
      flash[:success] = 'Request accepted.'
    end

    redirect_to user_path( current_user )
  end

  def deny_friend
    @request = Friendship.find( params[:friendship_id] )
    if @request.friend_id == current_user.id
      @request.destroy
      flash[:success] = 'Request deleted.'
    end

    redirect_to user_path( current_user )
  end

  def buy_gift
    user = User.find( params[:user_id] )
    buyer = User.find( params[:buyer_user_id] )

    if buyer.has_friend?( user )
      Gift.create(
        :user_id => user.id,
        :buyer_user_id => buyer.id,
        :name => params[:gift][:name],
        :description => params[:gift][:description]
      )
    end

    flash[:success] = 'Gift purchase logged.'

    redirect_to user_path( user )
  end

  def mark_gift_request_purchased
    gift_request = GiftRequest.find( params[:gift_request_id] )
    if !current_user.has_friend_with_id?( gift_request.user_id )
      flash[:error] = 'Can not purchase gift for non-friend'
    elsif gift_request.purchased?
      flash[:error] = 'This gift has already been marked as purchased'
    else
      gift_request.update_attribute( :purchased_by_user_id, current_user.id )
      if params[:copy_item] == 'true'
        Gift.create(
          :user_id => gift_request.user_id,
          :buyer_user_id => current_user.id,
          :name => gift_request.name,
          :description => gift_request.description
        )
      end
      flash[:success] = 'Gift marked as purchased'
    end

    redirect_to user_path( gift_request.user_id )
  end

  def delete_gift_request
    gift_request = GiftRequest.find( params[:gift_request_id] )

    if current_user_id?( gift_request.user_id )
      gift_request.destroy
      flash[:success] = 'Gift request destroyed.'
    else
      flash[:error] = 'Can not delete gift requests for other users'
    end

    redirect_to user_path( gift_request.user_id )
  end

  private
  def user_params
    params.require( :user ).permit( :full_name, :email, :password, :password_confirmation )
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_gift_request_fields.html.erb
<div class="fields gift-request-fields">
  <div class="form-group">
    <div class="col-form-label">
      <%= f.label :name, 'Gift name', :class => 'control-label' %>
    </div>
    <div class="col-form-input">
      <%= f.text_field :name, :class => 'form-control' %>
    </div>
  </div>
  <div class="form-group">
    <div class="col-form-label">
      <%= f.label :description, :class => 'control-label' %>
    </div>
    <div class="col-form-input">
      <%= f.text_area :description, :class => 'form-control' %>
    </div>
  </div>
</div>

app/views/users/index.html.erb
<div class="users-page">
  <div class="container">
    <div class="row-header">
      <div class="col-full">
        <h1>Find Friends</h1>
      </div>
    </div>
    <div class="row-search">
      <div class="col-search">
        <form onsubmit="submitSearch(); return false;">
          <div class="input-group">
            <%= text_field_tag :search, nil, :class => 'form-control' %>
            <div class="input-group-btn">
              <button class="btn btn-primary">Search</button>
            </div>
          </div>
        </form>
      </div>
    </div>
    <div class="row-user-list">
      <div class="col-user-list">
        <ul class="user-list">
          <% @users.each do |user| %>
            <li><%= link_to user.full_name, user_path( user ) %></li>
          <% end %>
        </ul>
      </div>
    </div>
  </div>
</div>

<script>
  function submitSearch() {
    searchTerm = $('#search').val();
    $.ajax({
      url: '<%= user_search_path %>',
      data: {
        search: searchTerm
      },
      success: function( data ) {
        userData = data;
        $('.user-list li').remove();
        $.each( data['users'], function( index, user ) {
          $('.user-list').append(
            '<li><a href=<%= users_path %>/' + user['id'] + '>' + user['full_name'] + ' (' + user['email'] + ')</a></li>'
          );
        });
        if( data['users'].length == 0 ) {
          $('.user-list').append(
            '<li>No users found...</li>'
          )
        }
      }
    });
  }
</script>

app/views/users/new.html.erb
<div class="new-user-page">
  <div class="container">
    <div class="row-header">
      <div class="col-full">
        <h1>Sign Up</h1>
      </div>
    </div>
    <div class="row-form">
      <div class="col-centered-form">
      <%= form_for @user, :html => { :class => "form-centered" } do |f| %>
        <%= render 'shared/error_messages', :model => @user %>
        <div class="form-group">
          <div class="col-form-label">
            <%= f.label :full_name, :class => "control-label" %>
          </div>
          <div class="col-form-input">
            <%= f.text_field :full_name, :class => "form-control" %>
          </div>
        </div>

        <div class="form-group">
          <div class="col-form-label">
            <%= f.label :email, :class => "control-label" %>
          </div>
          <div class="col-form-input">
            <%= f.text_field :email, :class => "form-control" %>
          </div>
        </div>

        <div class="form-group">
          <div class="col-form-label">
            <%= f.label :password, :class => "control-label" %>
          </div>
          <div class="col-form-input">
            <%= f.password_field :password, :class => "form-control" %>
          </div>
        </div>

        <div class="form-group">
          <div class="col-form-label">
            <%= f.label :password_confirmation, :class => "control-label" %>
          </div>
          <div class="col-form-input">
            <%= f.password_field :password_confirmation, :class => "form-control" %>
          </div>
        </div>

        <div class="form-group">
          <div class="col-submit">
            <%= f.submit "Create account", :class => "btn btn-submit" %>
          </div>
        </div>
      <% end %>
      </div>
    </div>
    <div class="row-note">
      <div class="col-full">
        Have account? Sign in <%= link_to 'here', signin_path %>
      </div>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<div class="show-user-page">
  <div class="container">
    <div class="row-header">
      <div class="col-full">
        <h1><%= @user.full_name %></h1>
        <h3><%= @user.email %></h3>
      </div>
    </div>

    <% if !current_user?( @user ) %>
      <div class="row-controls">
        <div class="col-full">
          <% if request = @user.pending_request( current_user ) %>
            <%= link_to 'Accept Request', accept_friend_path( :friendship_id => request.id ), :class => 'btn btn-primary', :method => 'post' %>
          <% elsif !@user.has_friend?( current_user ) %>
            <%= link_to 'Request Friend', add_friend_path( :friend_id => @user.id ), :class => 'btn btn-primary', :method => 'post' %>
          <% end %>
        </div>
      </div>
    <% end %>

    <% if current_user?( @user ) && @user.friend_requests.count > 0 %>
      <div class="row-pending-requests">
        <div class="col-full">
          <h3>Pending Requests</h3>
          <ul class="pending-requests-list">
            <% @user.friend_requests( :include_users => true ).sort_by( &:created_at ).each do |request| %>
              <li><%= request.user.full_name %> <%= link_to 'Accept', accept_friend_path( :friendship_id => request.id ), :method => :post %> <%= link_to 'Deny', deny_friend_path( :friendship_id => request.id ), :method => :post, :data => { :confirm => 'Are you sure?' } %></li>
            <% end %>
          </ul>
        </div>
      </div>
    <% end %>

    <div class="row-info">
      <% if current_user?( @user ) || @user.has_friend?( current_user ) %>
      <div class="col-info">
        <h3>
          <%= current_user?( @user ) ? 'My' : "#{@user.first_name}'s" %> Friends
        </h3>
        <ul class="info-list">
          <% @user.friends.each do |friend| %>
            <li><%= link_to friend.full_name, user_path( friend ) %></li>
          <% end %>
        </ul>
      </div>
      <% end %>

      <% if current_user?( @user ) || @user.has_friend?( current_user ) %>
      <div class="col-info">
        <h3>
          <%= current_user?( @user ) ? 'My' : "#{@user.first_name}'s" %> Gift Requests
        </h3>
        <ul class="gift-list">
          <% @user.gift_requests.sort_by( &:created_at ).each do |gift_request| %>
            <li>
              <p class="name"><%= gift_request.name %></p>
              <p class="description"><%= gift_request.description %></p>
              <% if current_user?( @user ) %>
                <%= link_to 'Delete request', delete_gift_request_path( :gift_request_id => gift_request.id ), :method => :delete, :data => { :confirm => 'Really delete this? (This can not be undone)' } %>
              <% else %>
                <% if gift_request.purchased? %>
                  (Purchased)
                <% else %>
                  <%= link_to 'Mark Purchased', mark_gift_request_purchased_path( :gift_request_id => gift_request.id ), :method => :post, :class => 'mark-gift-purchased-link' %>
                <% end %>
              <% end %>
            </li>
          <% end %>
        </ul>
        <% if current_user?( @user ) %>
          <%= form_for @user, :html => { :class => "form-centered", :onsubmit => "return checkGiftRequests( this );" } do |f| %>
            <div id="gift-requests"></div>
            <div class="form-group">
              <div class="col-submit">
                <%= link_to_add_fields 'Request Gift', f, :gift_requests, :layout_dir => 'users', :insert_element => '#gift-requests', :link_options => { :class => 'btn btn-submit' }  %>
                <%= f.submit 'Save Gift Requests', :class => 'btn btn-submit' %>
              </div>
            </div>
          <% end %>
        <% end %>
      </div>
      <% end %>

      <% if !current_user?( @user ) && @user.has_friend?( current_user ) %>
      <div class="col-info">
        <h3>Gifts Purchased For <%= @user.full_name %></h3>
        <ul class="gift-list">
          <% @user.gifts.sort_by( &:created_at ).each do |gift| %>
            <li>
              <p class="name"><%= gift.name %></p>
              <p class="description"><%= gift.description %></p>
              <p class="buyer">Purchased by: <%= link_to gift.buyer.full_name, user_path( gift.buyer ) %></p>
            </li>
          <% end %>
        </ul>
        <%= form_for :gift, :url => buy_user_gift_path( :user_id => @user.id, :buyer_user_id => current_user.id ), :html => { :class => 'form-centered' } do |f| %>
          <div class="form-group">
            <div class="col-form-label">
              <%= f.label :name, 'Gift name', :class => 'control-label' %>
            </div>
            <div class="col-form-input">
              <%= f.text_field :name, :class => 'form-control' %>
            </div>
          </div>
          <div class="form-group">
            <div class="col-form-label">
              <%= f.label :description, :class => 'control-label' %>
            </div>
            <div class="col-form-input">
              <%= f.text_area :description, :class => 'form-control' %>
            </div>
          </div>
          <div class="form-group">
            <div class="col-submit">
              <%= f.submit 'Submit Gift Purchased', :class => 'btn btn-submit' %>
            </div>
          </div>
        <% end %>
      </div>
    <% end %>

    <% if current_user?( @user ) %>
    <div class="col-info">
      <h3>My Purchased Gifts</h3>
      <ul class="gift-list">
        <% @user.gifts_purchased.sort_by( &:created_at ).each do |gift| %>
          <p class="name"><%= gift.name %></p>
          <p class="description"><%= gift.description %></p>
          <p class="buyer">Purchased for: <%= link_to gift.user.full_name, user_path( gift.user ) %></p>
        <% end %>
      </ul>
    </div>
    <% end %>
  </div>
</div>

<script>
  $(document).ready( function() {
    $('.mark-gift-purchased-link').click( function( event ) {
      if( confirm( 'Really mark this purchased? This can not be undone.' ) ) {
        if( confirm( 'Copy new item to purchased list?' ) ) {
          var href = $(sender).attr( 'href' ) + "&amp;copy_item=true";
          $(sender).attr( 'href', href );
        }
        return true;
      } else {
        event.preventDefault();
        return false;
      }
    });
  })

  function checkGiftRequests( sender ) {
    if( $(sender).find( '#gift-requests .gift-request-fields' ).size() > 0 ) {
      return true;
    } else {
      alert( 'Please add a gift before submitting.' );
      return false;
    }
  }
</script>