config/routes.rb
Wishlist::Application.routes.draw do
  root 'static_pages#root'

  match '/home', to: 'static_pages#home', via: :get, as: :home

  match '/signin', to: 'sessions#new', via: :get, as: :signin
  match '/signup', to: 'users#new', via: :get, as: :signup
  match '/signout', to: 'sessions#destroy', via: 'delete', as: :signout

  match '/users/search', to: 'users#search', via: 'get', as: :user_search
  match '/users/add_friend', to: 'users#add_friend', via: 'post', as: :add_friend
  match '/users/accept_friend', to: 'users#accept_friend', via: 'post', as: :accept_friend
  match '/users/deny_friend', to: 'users#deny_friend', via: 'post', as: :deny_friend
  match '/users/buy_gift', to: 'users#buy_gift', via: 'post', as: :buy_user_gift
  match '/users/mark_gift_request_purchased', to: 'users#mark_gift_request_purchased', via: 'post', as: :mark_gift_request_purchased
  match '/users/delete_gift_request', to: 'users#delete_gift_request', via: 'delete', as: :delete_gift_request

  resources :users, only: [:new, :create, :show, :index, :update]
  resources :sessions, only: [:new, :create, :destroy]
end

app/views/shared/_error_messages.html.erb
<% if !model.nil? && model.errors.any? %>
  <div id="error-explanation">
    <div class="alert alert-error">
      The form contains <%= pluralize(model.errors.count, "error") %>.
    </div>
    <ul>
    <% model.errors.full_messages.each do |msg| %>
      <li>* <%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_flash.html.erb
<div class="container flash-messages">
  <% flash.each do |key, value| %>
    <div class="alert alert-<%= key %>"><%= value %></div>
  <% end %>
</div>

app/views/shared/_footer.html.erb
<div class="wl-footer">
  <div class="footer-content">
  </div>
</div>

app/views/shared/_header.html.erb
<header>
  <nav class="wl-header" role="navigation">
    <div class="container">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#menu-collapse">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <%= link_to 'Wishlist', home_path, :class => 'header-brand' %>
      </div>
      <div class="collapse navbar-collapse" id="menu-collapse">
        <ul class="nav navbar-nav navbar-right header-links">
          <% if signed_in? %>
            <li><%= link_to 'Find Friends', users_path, :class => 'header-link' %></li>
            <li><%= link_to current_user.header_link_text, user_path( current_user ), :class => 'header-link' %></li>
            <li><%= link_to 'Sign Out', signout_path, :class => 'header-link', :method => :delete %></li>
          <% else %>
            <li><%= link_to 'Sign In', signin_path, :class => 'header-link' %></li>
            <li><%= link_to 'Sign Up', signup_path, :class => 'header-link' %></li>
          <% end %>
        </ul>
      </div>
    </div>
  </nav>
</header>